<a href="https://colab.research.google.com/github/Harsh28-raj/dl_projects/blob/main/fnl%2C_legal_case_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.0)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.2.25)

In [3]:
!kaggle datasets download -d vangap/indian-supreme-court-judgments

Dataset URL: https://www.kaggle.com/datasets/vangap/indian-supreme-court-judgments
License(s): CC-BY-NC-SA-4.0
Downloading indian-supreme-court-judgments.zip to /content
100% 4.77G/4.77G [01:00<00:00, 85.3MB/s]

In [4]:
!unzip indian-supreme-court-judgments.zip judgments.csv

Archive:  indian-supreme-court-judgments.zip
  inflating: judgments.csv

In [5]:
import pandas as pd

df=pd.read_csv("judgments.csv")

df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language
0,5-2021,J,MA-000083 - 2021,UNION OF INDIA,ASSOCIATION OF UNIFIED TELECOM SERVICEPROVIDER...,B. VIJAYALAKSHMI MENON,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,supremecourt/2021/5/5_2021_36_1501_28814_Judge...,NaN
1,28-2021,J,C.A. No.-000867-000867 - 2021,INDEX MEDICAL COLLEGE HOSPITAL AND RESEARCH CE...,THE STATE OF MADHYA PRADESH,NISHIT AGRAWAL,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,supremecourt/2021/28/28_2021_38_14_25922_Judge...,NaN
2,70-2020,J,Crl.A. No.-000167-000167 - 2021,ARCHANA RANA,THE STATE OF UTTAR PRADESH,SANJEEV MALHOTRA,NaN,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,supremecourt/2020/70/70_2020_36_1503_26554_Jud...,NaN
3,82-2021,J,SLP(C) No.-000811 - 2021,THE EMPLOYEES STATE INSURANCE CORPORATION,M/S. TEXMO INDUSTRIES,MRIDULA RAY BHARADWAJ,NaN,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,supremecourt/2021/82/82_2021_43_13_26745_Judge...,NaN
4,114-2021,J,C.A. No.-000390-000390 - 2021,KALOJI NARAYANA RAO UNIVERSITY OF HEALTH SCIENCES,SRIKEERTI REDDI PINGLE,VENKAT PALWAI LAW ASSOCIATES,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,supremecourt/2021/114/114_2021_38_1501_26229_J...,NaN

In [6]:
!rm indian-supreme-court-judgments.zip

In [32]:
df.sample(1000)

ValueError: Cannot take a larger sample than population when 'replace=False'

In [33]:
df.shape

(268, 20)

In [34]:
df.columns

Index(['diary_no', 'Judgement_type', 'case_no', 'pet', 'res', 'pet_adv',
       'res_adv', 'bench', 'judgement_by', 'judgment_dates', 'temp_link',
       'language', 'case_type', 'lawyer_exp', 'judge_exp', 'judge_count',
       'complexity', 'evidence', 'win_score', 'outcome'],
      dtype='object')

In [35]:
df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
148,5140-2009,J,C.A. No.-000138-000138 - 2012,MURALI ALIAS DHANANJAYAN,STATE OF KERALA,NISHE RAJEN SHONKER,G. PRAKASH,"HON'BLE MS. JUSTICE INDU MALHOTRA, HON'BLE MR....",HON'BLE MS. JUSTICE INDU MALHOTRA,02-03-2021,supremecourt_vernacular/2009/5140/5140_2009_12...,MAL,1,0.2,0.137931,3,13,0.834149,0.422055,0
317,12251-2012,J,C.A. No.-001537-001537 - 2016,R.JANKIAMMAL,S.K.KUMARASWAMY (D) THR.LRS.,VIKAS MEHTA,SHOBHA RAMAMOORTHY,"HON'BLE MR. JUSTICE ASHOK BHUSHAN, HON'BLE MR....",HON'BLE MR. JUSTICE ASHOK BHUSHAN,30-06-2021,supremecourt_vernacular/2012/12251/12251_2012_...,TAM,1,0.2,0.413793,4,19,0.556742,0.400750,0
339,12996-2008,J,C.A. No.-000202-000202 - 2012,GOVERNMENT OF KERALA,MOTHER SUPERIOR ADORATION CONVENT,C. K. SASI,M. P. VINOD,"HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN, HON...",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,01-03-2021,supremecourt_vernacular/2008/12996/12996_2008_...,MAL,1,0.2,0.103448,3,11,0.691982,0.411249,0
379,14414-2014,J,C.A. No.-005041-005041 - 2021,SUPERTECH LTD,EMERALD COURT OWNER RESIDENT WELFARE ASSOCIATION,R. CHANDRACHUD,MILIND KUMAR,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,31-08-2021,supremecourt_vernacular/2014/14414/14414_2014_...,HIN,1,0.6,1.000000,4,25,0.589550,0.677910,0
386,14641-2008,J,C.A. No.-006255-006255 - 2021,SUSHIL KUMAR TRIPATHI,JAGADGURU RAM BHADRACHARYA HANDI UNI&ANR,AMIT ANAND TIWARI,KAMLENDRA MISHRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MRS. JUSTIC...",HON'BLE THE CHIEF JUSTICE,29-10-2021,supremecourt_vernacular/2008/14641/14641_2008_...,HIN,1,0.4,1.000000,3,21,0.720621,0.659362,1

In [36]:
df.dropna()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
148,5140-2009,J,C.A. No.-000138-000138 - 2012,MURALI ALIAS DHANANJAYAN,STATE OF KERALA,NISHE RAJEN SHONKER,G. PRAKASH,"HON'BLE MS. JUSTICE INDU MALHOTRA, HON'BLE MR....",HON'BLE MS. JUSTICE INDU MALHOTRA,02-03-2021,supremecourt_vernacular/2009/5140/5140_2009_12...,MAL,1,0.2,0.137931,3,13,0.834149,0.422055,0
317,12251-2012,J,C.A. No.-001537-001537 - 2016,R.JANKIAMMAL,S.K.KUMARASWAMY (D) THR.LRS.,VIKAS MEHTA,SHOBHA RAMAMOORTHY,"HON'BLE MR. JUSTICE ASHOK BHUSHAN, HON'BLE MR....",HON'BLE MR. JUSTICE ASHOK BHUSHAN,30-06-2021,supremecourt_vernacular/2012/12251/12251_2012_...,TAM,1,0.2,0.413793,4,19,0.556742,0.400750,0
339,12996-2008,J,C.A. No.-000202-000202 - 2012,GOVERNMENT OF KERALA,MOTHER SUPERIOR ADORATION CONVENT,C. K. SASI,M. P. VINOD,"HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN, HON...",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,01-03-2021,supremecourt_vernacular/2008/12996/12996_2008_...,MAL,1,0.2,0.103448,3,11,0.691982,0.411249,0
379,14414-2014,J,C.A. No.-005041-005041 - 2021,SUPERTECH LTD,EMERALD COURT OWNER RESIDENT WELFARE ASSOCIATION,R. CHANDRACHUD,MILIND KUMAR,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,31-08-2021,supremecourt_vernacular/2014/14414/14414_2014_...,HIN,1,0.6,1.000000,4,25,0.589550,0.677910,0
386,14641-2008,J,C.A. No.-006255-006255 - 2021,SUSHIL KUMAR TRIPATHI,JAGADGURU RAM BHADRACHARYA HANDI UNI&ANR,AMIT ANAND TIWARI,KAMLENDRA MISHRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MRS. JUSTIC...",HON'BLE THE CHIEF JUSTICE,29-10-2021,supremecourt_vernacular/2008/14641/14641_2008_...,HIN,1,0.4,1.000000,3,21,0.720621,0.659362,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25670,33288-2008,J,C.A. No.-008642-008642 - 2009,M.ARUMUGAM,AMMANIAMMAL AND ORS.,P. V. DINESH,REVATHY RAGHAVAN,"HON'BLE MR. JUSTICE DEEPAK GUPTA, HON'BLE MR. ...",HON'BLE MR. JUSTICE DEEPAK GUPTA,08-01-2020,supremecourt_vernacular/2008/33288/33288_2008_...,TAM,1,0.4,0.517241,3,21,0.536981,0.477807,0
25672,33360-2009,J,Crl.A. No.-000779-000779 - 2010,DHANPAL,STATE NCT OF DELHI,ARUN K. SINHA,ANIL KATIYAR,"HON'BLE MR. JUSTICE DEEPAK GUPTA, HON'BLE MR. ...",HON'BLE MR. JUSTICE ANIRUDDHA BOSE,27-04-2020,supremecourt_vernacular/2009/33360/33360_2009_...,HIN,0,0.2,0.137931,3,16,0.572031,0.340785,0
25691,34078-2014,J,Crl.A. No.-000335-000335 - 2015,AMAR SINGH,THE STATE (NCT OF DELHI),NIKHIL GOEL,B. KRISHNA PRASAD,"HON'BLE MR. JUSTICE A.M. KHANWILKAR, HON'BLE M...",HON'BLE MR. JUSTICE KRISHNA MURARI,12-10-2020,supremecourt_vernacular/2014/34078/34078_2014_...,HIN,0,0.2,0.103448,4,26,0.458402,0.259638,1
25697,34682-2009,J,C.A. No.-008350-008350 - 2009,KERALA STATE ELECTRICITY BOARD REP. BY ITS SEC...,PRINCIPAL SIR SYED INSTITUTE FOR TECHNICAL STU...,P. V. DINESH,E. M. S. ANAM,"HON'BLE MR. JUSTICE DEEPAK GUPTA, HON'BLE MR. ...",HON'BLE MR. JUSTICE ANIRUDDHA BOSE,20-02-2020,supremecourt_vernacular/2009/34682/34682_2009_...,MAL,1,0.4,0.137931,3,19,0.803294,0.427301,0
25762,39751-2015,J,Crl.A. No.-000488-000489 - 2017,MUSTAK @ KANIO AHMED SHAIKH,STATE OF GUJARAT,MOHIT D. RAM,HEMANTIKA WAHI,"HON'BLE MRS. JUSTICE R. BANUMATHI, HON'BLE MS....",HON'BLE MS. JUSTICE INDIRA BANERJEE,18-06-2020,supremecourt_vernacular/2015/39751/39751_2015_...,GUJ,0,0.2,0.241379,3,21,0.687027,0.365057,0

In [37]:
df.shape

(268, 20)

In [38]:
df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
148,5140-2009,J,C.A. No.-000138-000138 - 2012,MURALI ALIAS DHANANJAYAN,STATE OF KERALA,NISHE RAJEN SHONKER,G. PRAKASH,"HON'BLE MS. JUSTICE INDU MALHOTRA, HON'BLE MR....",HON'BLE MS. JUSTICE INDU MALHOTRA,02-03-2021,supremecourt_vernacular/2009/5140/5140_2009_12...,MAL,1,0.2,0.137931,3,13,0.834149,0.422055,0
317,12251-2012,J,C.A. No.-001537-001537 - 2016,R.JANKIAMMAL,S.K.KUMARASWAMY (D) THR.LRS.,VIKAS MEHTA,SHOBHA RAMAMOORTHY,"HON'BLE MR. JUSTICE ASHOK BHUSHAN, HON'BLE MR....",HON'BLE MR. JUSTICE ASHOK BHUSHAN,30-06-2021,supremecourt_vernacular/2012/12251/12251_2012_...,TAM,1,0.2,0.413793,4,19,0.556742,0.400750,0
339,12996-2008,J,C.A. No.-000202-000202 - 2012,GOVERNMENT OF KERALA,MOTHER SUPERIOR ADORATION CONVENT,C. K. SASI,M. P. VINOD,"HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN, HON...",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,01-03-2021,supremecourt_vernacular/2008/12996/12996_2008_...,MAL,1,0.2,0.103448,3,11,0.691982,0.411249,0
379,14414-2014,J,C.A. No.-005041-005041 - 2021,SUPERTECH LTD,EMERALD COURT OWNER RESIDENT WELFARE ASSOCIATION,R. CHANDRACHUD,MILIND KUMAR,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,31-08-2021,supremecourt_vernacular/2014/14414/14414_2014_...,HIN,1,0.6,1.000000,4,25,0.589550,0.677910,0
386,14641-2008,J,C.A. No.-006255-006255 - 2021,SUSHIL KUMAR TRIPATHI,JAGADGURU RAM BHADRACHARYA HANDI UNI&ANR,AMIT ANAND TIWARI,KAMLENDRA MISHRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MRS. JUSTIC...",HON'BLE THE CHIEF JUSTICE,29-10-2021,supremecourt_vernacular/2008/14641/14641_2008_...,HIN,1,0.4,1.000000,3,21,0.720621,0.659362,1

In [39]:
df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,win_score,outcome
148,5140-2009,J,C.A. No.-000138-000138 - 2012,MURALI ALIAS DHANANJAYAN,STATE OF KERALA,NISHE RAJEN SHONKER,G. PRAKASH,"HON'BLE MS. JUSTICE INDU MALHOTRA, HON'BLE MR....",HON'BLE MS. JUSTICE INDU MALHOTRA,02-03-2021,supremecourt_vernacular/2009/5140/5140_2009_12...,MAL,1,0.2,0.137931,3,13,0.834149,0.422055,0
317,12251-2012,J,C.A. No.-001537-001537 - 2016,R.JANKIAMMAL,S.K.KUMARASWAMY (D) THR.LRS.,VIKAS MEHTA,SHOBHA RAMAMOORTHY,"HON'BLE MR. JUSTICE ASHOK BHUSHAN, HON'BLE MR....",HON'BLE MR. JUSTICE ASHOK BHUSHAN,30-06-2021,supremecourt_vernacular/2012/12251/12251_2012_...,TAM,1,0.2,0.413793,4,19,0.556742,0.400750,0
339,12996-2008,J,C.A. No.-000202-000202 - 2012,GOVERNMENT OF KERALA,MOTHER SUPERIOR ADORATION CONVENT,C. K. SASI,M. P. VINOD,"HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN, HON...",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,01-03-2021,supremecourt_vernacular/2008/12996/12996_2008_...,MAL,1,0.2,0.103448,3,11,0.691982,0.411249,0
379,14414-2014,J,C.A. No.-005041-005041 - 2021,SUPERTECH LTD,EMERALD COURT OWNER RESIDENT WELFARE ASSOCIATION,R. CHANDRACHUD,MILIND KUMAR,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,31-08-2021,supremecourt_vernacular/2014/14414/14414_2014_...,HIN,1,0.6,1.000000,4,25,0.589550,0.677910,0
386,14641-2008,J,C.A. No.-006255-006255 - 2021,SUSHIL KUMAR TRIPATHI,JAGADGURU RAM BHADRACHARYA HANDI UNI&ANR,AMIT ANAND TIWARI,KAMLENDRA MISHRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MRS. JUSTIC...",HON'BLE THE CHIEF JUSTICE,29-10-2021,supremecourt_vernacular/2008/14641/14641_2008_...,HIN,1,0.4,1.000000,3,21,0.720621,0.659362,1

In [40]:
lawyer_counts=df['pet_adv'].value_counts()

In [41]:
lawyer_counts

pet_adv
C. D. SINGH             5
SWARUPAMA CHATURVEDI    4
SUSHIL BALWADA          4
SHIBASHISH MISRA        4
K. V. VIJAYAKUMAR       4
                       ..
PRAVEEN KUMAR           1
PREM PRAKASH            1
ARUN K. SINHA           1
NIKHIL GOEL             1
MOHIT D. RAM            1
Name: count, Length: 196, dtype: int64

In [42]:
import numpy as np

In [43]:
df=df.dropna()

In [44]:
print(df.columns)

Index(['diary_no', 'Judgement_type', 'case_no', 'pet', 'res', 'pet_adv',
       'res_adv', 'bench', 'judgement_by', 'judgment_dates', 'temp_link',
       'language', 'case_type', 'lawyer_exp', 'judge_exp', 'judge_count',
       'complexity', 'evidence', 'win_score', 'outcome'],
      dtype='object')

In [45]:
def get_case_type(x):

    x=str(x)

    if "Crl" in x:
        return 0
    elif "C.A" in x:
        return 1
    elif "SLP" in x:
        return 2
    elif "W.P" in x:
        return 3
    else:
        return 4

df['case_type']=df['case_no'].apply(get_case_type)

In [46]:
lawyer_counts=df['pet_adv'].value_counts()

df['lawyer_exp']=df['pet_adv'].map(lawyer_counts)

df['lawyer_exp']=df['lawyer_exp']/df['lawyer_exp'].max()

In [47]:
judge_counts=df['judgement_by'].value_counts()

df['judge_exp']=df['judgement_by'].map(judge_counts)

df['judge_exp']=df['judge_exp']/df['judge_exp'].max()

In [48]:
df['judge_count']=df['bench'].str.count("JUSTICE")+1

In [49]:
df['complexity'] = df['judge_count']*2 + np.random.randint(5,20,len(df))

df['evidence']=np.random.uniform(0.4,0.9,len(df))

df['win_score']=(
0.30*df['lawyer_exp']+
0.30*df['judge_exp']+
0.20*df['evidence']+
0.20*(1/(df['complexity']/10))
)

df['win_score']=df['win_score'].clip(0.05,0.95)

df['outcome']=np.random.binomial(1,df['win_score'])

In [50]:
FEATURES=[
'case_type',
'lawyer_exp',
'judge_exp',
'judge_count',
'complexity',
'evidence'
]
X=df[FEATURES]

y=df['outcome']

In [54]:
from sklearn.preprocessing import StandardScaler

In [55]:
from sklearn.model_selection import train_test_split

X=df[FEATURES]

y=df['outcome']

X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.2,stratify=y,random_state=42
)

scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

log_model.fit(X_train,y_train)

LogisticRegression(C=0.3, class_weight='balanced', max_iter=2000,
                   random_state=42)

In [56]:
from sklearn.linear_model import LogisticRegression

log_model=LogisticRegression(
max_iter=2000,
C=0.3,
class_weight='balanced',
random_state=42
)
log_model.fit(X_train,y_train)

LogisticRegression(C=0.3, class_weight='balanced', max_iter=2000,
                   random_state=42)

In [57]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
n_estimators=300,
max_depth=10,
random_state=42
)

rf.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, n_estimators=300, random_state=42)

In [58]:
from xgboost import XGBClassifier

xgb=XGBClassifier(
n_estimators=300,
learning_rate=0.05,
max_depth=6,
random_state=42
)

xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [59]:
from sklearn.metrics import accuracy_score

log_pred=log_model.predict(X_test)

rf_pred=rf.predict(X_test)

xgb_pred=xgb.predict(X_test)

print("Logistic:",accuracy_score(y_test,log_pred))

print("RF:",accuracy_score(y_test,rf_pred))

print("XGB:",accuracy_score(y_test,xgb_pred))

Logistic: 0.6296296296296297
RF: 0.46296296296296297
XGB: 0.5185185185185185

In [60]:
prob=log_model.predict_proba(X_test)

print(prob[:5])

[[0.58808528 0.41191472]
 [0.58330265 0.41669735]
 [0.22595301 0.77404699]
 [0.4398177  0.5601823 ]
 [0.4491889  0.5508111 ]]

In [61]:
def predict_case(case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence):

    import numpy as np

    lawyer_exp=np.clip(lawyer_exp,0,1)

    judge_exp=np.clip(judge_exp,0,1)

    evidence=np.clip(evidence,0,1)

    judge_count=max(1,judge_count)

    complexity=max(1,complexity)

    sample=pd.DataFrame(
        [[case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence]],
        columns=FEATURES
    )

    sample=scaler.transform(sample)

    prob=log_model.predict_proba(sample)

    win=float(prob[0][1]*100)

    if win>70:
        strength="Strong"

    elif win>50:
        strength="Moderate"

    else:
        strength="Weak"

    return {
        "Win probability":round(win,2),
        "Case strength":strength
    }

In [62]:
predict_case(1,0.3,0.5,3,18,0.7)

{'Win probability': 50.6, 'Case strength': 'Moderate'}

In [63]:
from sklearn.metrics import accuracy_score,classification_report,f1_score

models={
    "Logistic Regression":log_model,
    "Random Forest":rf,
    "XGBoost":xgb
}

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    print("======",name,"======")

    print("Accuracy:",round(acc*100,2),"%")

    print("F1 Score:",round(f1*100,2),"%")

    print(classification_report(y_test,pred))

    print()

====== Logistic Regression ======
Accuracy: 62.96 %
F1 Score: 61.54 %
              precision    recall  f1-score   support

           0       0.62      0.67      0.64        27
           1       0.64      0.59      0.62        27

    accuracy                           0.63        54
   macro avg       0.63      0.63      0.63        54
weighted avg       0.63      0.63      0.63        54


====== Random Forest ======
Accuracy: 46.3 %
F1 Score: 47.27 %
              precision    recall  f1-score   support

           0       0.46      0.44      0.45        27
           1       0.46      0.48      0.47        27

    accuracy                           0.46        54
   macro avg       0.46      0.46      0.46        54
weighted avg       0.46      0.46      0.46        54


====== XGBoost ======
Accuracy: 51.85 %
F1 Score: 51.85 %
              precision    recall  f1-score   support

           0       0.52      0.52      0.52        27
           1       0.52      0.52      0.52        27

    accuracy                           0.52        54
   macro avg       0.52      0.52      0.52        54
weighted avg       0.52      0.52      0.52        54

In [64]:
results=[]

for name,model in models.items():

    pred=model.predict(X_test)

    acc=accuracy_score(y_test,pred)

    f1=f1_score(y_test,pred)

    results.append([name,acc,f1])

results_df=pd.DataFrame(
results,
columns=["Model","Accuracy","F1 Score"]
)

results_df

                 Model  Accuracy  F1 Score
0  Logistic Regression  0.629630  0.615385
1        Random Forest  0.462963  0.472727
2              XGBoost  0.518519  0.518519

In [65]:
from sklearn.metrics import roc_auc_score

for name,model in models.items():

    prob=model.predict_proba(X_test)[:,1]

    auc=roc_auc_score(y_test,prob)

    print(name,"ROC AUC:",round(auc,3))

Logistic Regression ROC AUC: 0.616
Random Forest ROC AUC: 0.494
XGBoost ROC AUC: 0.535

In [66]:
predict_case(1,0,0,0,18,0.7)

{'Win probability': 19.68, 'Case strength': 'Weak'}

In [67]:
predict_case(0,0,4,0,0,0)

{'Win probability': 60.97, 'Case strength': 'Moderate'}

In [69]:
import pickle

pickle.dump(log_model,open("legal_model.pkl","wb"))

pickle.dump(scaler,open("scaler.pkl","wb"))

pickle.dump(FEATURES,open("features.pkl","wb"))

In [70]:
from google.colab import files

files.download("legal_model.pkl")

files.download("scaler.pkl")

files.download("features.pkl")