<a href="https://colab.research.google.com/github/Harsh28-raj/dl_projects/blob/main/legal_case_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!mkdir -p ~/.kaggle

!cp kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.4.5)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.5.1)

In [3]:
!kaggle datasets download -d vangap/indian-supreme-court-judgments

Dataset URL: https://www.kaggle.com/datasets/vangap/indian-supreme-court-judgments
License(s): CC-BY-NC-SA-4.0
Downloading indian-supreme-court-judgments.zip to /content
100% 4.76G/4.77G [01:21<00:00, 38.2MB/s]
100% 4.77G/4.77G [01:21<00:00, 63.1MB/s]

In [4]:
!unzip indian-supreme-court-judgments.zip judgments.csv

Archive:  indian-supreme-court-judgments.zip
  inflating: judgments.csv

In [5]:
import pandas as pd

df=pd.read_csv("judgments.csv")

df.head()

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language
0,5-2021,J,MA-000083 - 2021,UNION OF INDIA,ASSOCIATION OF UNIFIED TELECOM SERVICEPROVIDER...,B. VIJAYALAKSHMI MENON,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,supremecourt/2021/5/5_2021_36_1501_28814_Judge...,NaN
1,28-2021,J,C.A. No.-000867-000867 - 2021,INDEX MEDICAL COLLEGE HOSPITAL AND RESEARCH CE...,THE STATE OF MADHYA PRADESH,NISHIT AGRAWAL,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,supremecourt/2021/28/28_2021_38_14_25922_Judge...,NaN
2,70-2020,J,Crl.A. No.-000167-000167 - 2021,ARCHANA RANA,THE STATE OF UTTAR PRADESH,SANJEEV MALHOTRA,NaN,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,supremecourt/2020/70/70_2020_36_1503_26554_Jud...,NaN
3,82-2021,J,SLP(C) No.-000811 - 2021,THE EMPLOYEES STATE INSURANCE CORPORATION,M/S. TEXMO INDUSTRIES,MRIDULA RAY BHARADWAJ,NaN,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,supremecourt/2021/82/82_2021_43_13_26745_Judge...,NaN
4,114-2021,J,C.A. No.-000390-000390 - 2021,KALOJI NARAYANA RAO UNIVERSITY OF HEALTH SCIENCES,SRIKEERTI REDDI PINGLE,VENKAT PALWAI LAW ASSOCIATES,NaN,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,supremecourt/2021/114/114_2021_38_1501_26229_J...,NaN

In [6]:
!rm indian-supreme-court-judgments.zip

In [7]:
df.sample(1000)

,diary_no,Judgement_type,case_no,pet,res,pet_adv,res_adv,bench,judgement_by,judgment_dates,temp_link,language
12620,60644-1998,J,- 0,DR. DURYODHAN SAHU AND ORS.,JITENDRA KUMAR MISHRA AND ORS.,NaN,NaN,"S.C.AGARWAL,S. SAGHIR AHMAD,M SRINIVASAN.",NaN,25-08-1998,jonew/judis/13058.pdf,NaN
38663,12603-2000,J,Crl.A. No.-000465-000465 - 2001,STATE OF TAMIL NADU,R. SASIKUMAR,V. G. PRAGASAM,K. K. MANI,"ARIJIT PASAYAT,P. SATHASIVAM,AFTAB ALAM, ,",NaN,09-07-2008,jonew/judis/31842.pdf,NaN
11618,10266-1994,J,C.A. No.-010231-010231 - 1996,NAJAMAL HUSSAIN MAHEDI,STATE OF MAHARASHTRA .,NaN,NaN,G.B. PATTANAIK (J),NaN,09-08-1996,jonew/judis/15314.pdf,NaN
9004,7459-2018,J,W.P.(C) No.-000231 - 2018,MEDICAL COUNCIL OF INDIA,THE STATE OF KERALA,GAURAV SHARMA,NaN,"HON'BLE MR. JUSTICE ARUN MISHRA, HON'BLE MR. J...",HON'BLE MR. JUSTICE ARUN MISHRA,12-09-2018,supremecourt/2018/7459/7459_2018_Judgement_12-...,NaN
28277,60109-1966,J,- 0,S. SANYAL,GIAN CHAND,NaN,NaN,NaN,NaN,14-09-1967,jonew/judis/2286.pdf,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
8241,23750-2016,J,C.A. No.-017974-017974 - 2017,MAHARASHTRA FOREST GUARDS AND FORESTERS UNION ...,THE STATE OF MAHARASHTRA AND ORS.,ANAGHA S. DESAI,NaN,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MRS...",HON'BLE MR. JUSTICE KURIAN JOSEPH,03-11-2017,supremecourt/2016/23750/23750_2016_Judgement_0...,NaN
2942,3672-2012,J,Crl.A. No.-001301-001301 - 2013,GULAB CHAND,PRADEEP KR.DEHALWAL,K. RAJEEV,PRAGATI NEEKHRA,"H.L. DATTU,SUDHANSU JYOTI MUKHOPADHAYA,M.Y. EQBAL",NaN,29-08-2013,jonew/judis/40804.pdf,NaN
17252,89000-1993,J,C.A. No.-007873-007873 - 1995,STATE OF U.P.,RAM KHELAWAN .,NaN,ABHA R. SHARMA,"RAMASWAMY,K.",NaN,17-08-1995,jonew/judis/10616.pdf,NaN
33731,886-1999,J,C.A. No.-007384-007384 - 2000,PRATAP SINGH,"REGISTRAR, I.G.I.T.",NaN,RAJ KUMAR MEHTA,NaN,NaN,15-12-2000,jonew/judis/17378.pdf,NaN
8158,21194-2016,J,C.A. No.-012743-012743 - 2017,KARAN SINGH,DELHI TRANSPORT CORPORATION,PETITIONER-IN-PERSON,ASHA GOPALAN NAIR,"HON'BLE MR. JUSTICE MOHAN M. SHANTANAGOUDAR, H...",NaN,13-09-2017,supremecourt/2016/21194/21194_2016_Order_13-Se...,NaN

In [8]:
df.shape

(47400, 12)

In [9]:
df.columns

Index(['diary_no', 'Judgement_type', 'case_no', 'pet', 'res', 'pet_adv',
       'res_adv', 'bench', 'judgement_by', 'judgment_dates', 'temp_link',
       'language'],
      dtype='object')

In [10]:
df=df.drop([
'diary_no',
'Judgement_type',
'pet',
'res',
'res_adv',
'temp_link',
'language'
],axis=1)

In [11]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021

In [12]:
df.dropna()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021
...,...,...,...,...,...
47105,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016
47106,C.A. No.-004715-004715 - 2011,SANJAY KAPUR,"HON'BLE MR. JUSTICE T.S. THAKUR, HON'BLE MR. J...",HON'BLE MR. JUSTICE A.M. KHANWILKAR,16-09-2016
47169,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016
47170,C.A. No.-010860-010860 - 2016,CYRIL AMARCHAND MANGALDAS AOR,"HON'BLE MR. JUSTICE KURIAN JOSEPH, HON'BLE MR....",HON'BLE MR. JUSTICE ROHINTON FALI NARIMAN,15-11-2016
47236,C.A. No.-010951-010951 - 2016,SHARMILA UPADHYAY,"HON'BLE MR. JUSTICE A.K. SIKRI, HON'BLE MRS. J...",HON'BLE MR. JUSTICE A.K. SIKRI,14-12-2016

In [13]:
df.shape

(47400, 5)

In [14]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021

In [15]:
def get_case_type(x):

    x=str(x)

    if "Crl" in x:
        return 0

    elif "C.A" in x:
        return 1

    elif "SLP" in x:
        return 2

    elif "W.P" in x:
        return 3

    else:
        return 4

df['case_type']=df['case_no'].apply(get_case_type)

In [16]:
df.head()

,case_no,pet_adv,bench,judgement_by,judgment_dates,case_type
0,MA-000083 - 2021,B. VIJAYALAKSHMI MENON,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,23-07-2021,4
1,C.A. No.-000867-000867 - 2021,NISHIT AGRAWAL,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE L. NAGESWARA RAO,03-02-2021,1
2,Crl.A. No.-000167-000167 - 2021,SANJEEV MALHOTRA,"HON'BLE THE CHIEF JUSTICE, HON'BLE MR. JUSTICE...",HON'BLE THE CHIEF JUSTICE,01-03-2021,0
3,SLP(C) No.-000811 - 2021,MRIDULA RAY BHARADWAJ,"HON'BLE MS. JUSTICE INDIRA BANERJEE, HON'BLE M...",HON'BLE MS. JUSTICE INDIRA BANERJEE,08-03-2021,2
4,C.A. No.-000390-000390 - 2021,VENKAT PALWAI LAW ASSOCIATES,"HON'BLE MR. JUSTICE L. NAGESWARA RAO, HON'BLE ...",HON'BLE MR. JUSTICE S. RAVINDRA BHAT,16-02-2021,1

In [17]:
lawyer_counts=df['pet_adv'].value_counts()

df['lawyer_exp']=df['pet_adv'].map(lawyer_counts)

In [18]:
df['lawyer_exp']=df['lawyer_exp']/df['lawyer_exp'].max()

In [19]:
judge_counts=df['judgement_by'].value_counts()

df['judge_exp']=df['judgement_by'].map(judge_counts)

df['judge_exp']=df['judge_exp']/df['judge_exp'].max()

In [20]:
df['judge_count']=df['bench'].str.count("JUSTICE")+1

In [21]:
df['year']=df['judgment_dates'].str[-4:]

df['year']=pd.to_numeric(df['year'])

In [22]:
df['year']=df['year']/df['year'].max()

In [23]:
import numpy as np

df['complexity']=(
df['judge_count']*2+
np.random.randint(5,20,len(df))
)

In [24]:
df['evidence']=np.random.uniform(0.4,0.9,len(df))

In [39]:
df['win_score']=(
0.30*df['lawyer_exp']+
0.30*df['judge_exp']+
0.20*df['evidence']+
0.20*(1/(df['complexity']/10))
)

In [26]:
df['outcome'] = (df['win_score'].rank(pct=True) > 0)

In [27]:
df=df[[

'case_type',
'lawyer_exp',
'judge_exp',
'judge_count',
'complexity',
'evidence',
'outcome'

]]

In [28]:
df.head()

,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,outcome
0,4,0.1025,0.180339,4.0,16.0,0.874947,True
1,1,0.0175,0.180339,3.0,21.0,0.822837,True
2,0,0.0475,1.000000,3.0,12.0,0.461989,True
3,2,0.0850,0.087458,3.0,24.0,0.646839,True
4,1,0.0275,0.086102,3.0,25.0,0.573831,True

In [29]:
df.describe()

,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence
count,47400.000000,25396.000000,8599.000000,35050.000000,35050.000000,47400.000000
mean,1.802257,0.157672,0.320856,1.540228,15.100485,0.649475
std,1.558629,0.186587,0.341832,0.972793,4.719348,0.144256
min,0.000000,0.002500,0.000678,1.000000,7.000000,0.400002
25%,1.000000,0.045000,0.088136,1.000000,11.000000,0.524156
50%,1.000000,0.100000,0.151186,1.000000,15.000000,0.649832
75%,4.000000,0.187500,0.576271,1.000000,19.000000,0.773953
max,4.000000,1.000000,1.000000,8.000000,31.000000,0.900000

In [30]:
X=df.drop("outcome",axis=1)

y=df["outcome"]

In [31]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(
n_estimators=200
)

model.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200)

In [33]:
from sklearn.metrics import accuracy_score

pred=model.predict(X_test)

print("Accuracy:",
accuracy_score(y_test,pred))

Accuracy: 1.0

In [34]:
sample=X_test.iloc[0:1]

prob=model.predict_proba(sample)

print("Win probability:",
round(prob[0][1]*100,2),"%")

print("Loss probability:",
round(prob[0][0]*100,2),"%")

Win probability: 0.0 %
Loss probability: 100.0 %

In [35]:
for i in range(5):

    sample=X_test.iloc[i:i+1]

    prob=model.predict_proba(sample)

    print("Case",i)

    print("Win:",
    round(prob[0][1]*100,2),"%")

    print("Lose:",
    round(prob[0][0]*100,2),"%")

    print()

Case 0
Win: 0.0 %
Lose: 100.0 %

Case 1
Win: 0.0 %
Lose: 100.0 %

Case 2
Win: 0.0 %
Lose: 100.0 %

Case 3
Win: 0.0 %
Lose: 100.0 %

Case 4
Win: 0.0 %
Lose: 100.0 %

In [40]:
df = df.sort_values('win_score')

df['outcome'] = 0

df.iloc[len(df)//2:, df.columns.get_loc('outcome')] = 1

df['outcome'] = df['outcome'].astype(int)

In [41]:
df["outcome"].value_counts()

outcome
0    23700
1    23700
Name: count, dtype: int64

In [42]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.5
1    0.5
Name: proportion, dtype: float64

In [43]:
df.head()

,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,outcome,win_score
23108,1,0.0075,0.002712,3.0,24.0,0.428268,0,0.172050
7691,0,0.0200,0.017627,3.0,24.0,0.404585,0,0.175539
24664,1,0.0150,0.050847,3.0,25.0,0.410489,0,0.181852
8845,4,0.0150,0.044068,3.0,24.0,0.404477,0,0.181949
22645,1,0.0200,0.016271,3.0,24.0,0.444205,0,0.183056

In [44]:
df['win_score'].describe()

count    8094.000000
mean        0.377050
std         0.118771
min         0.172050
25%         0.287947
50%         0.342166
75%         0.450758
max         0.899714
Name: win_score, dtype: float64

In [45]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.5
1    0.5
Name: proportion, dtype: float64

In [46]:
df=df.dropna()
df=df.drop_duplicates()

In [47]:
df.head()

,case_type,lawyer_exp,judge_exp,judge_count,complexity,evidence,outcome,win_score
23108,1,0.0075,0.002712,3.0,24.0,0.428268,0,0.172050
7691,0,0.0200,0.017627,3.0,24.0,0.404585,0,0.175539
24664,1,0.0150,0.050847,3.0,25.0,0.410489,0,0.181852
8845,4,0.0150,0.044068,3.0,24.0,0.404477,0,0.181949
22645,1,0.0200,0.016271,3.0,24.0,0.444205,0,0.183056

In [49]:
df = df.drop(['complexity','evidence','win_score'], axis=1)

In [51]:
X = X.fillna(0)

In [53]:
prob=model.predict_proba(X_test)

In [76]:
df.head()

       case_type  lawyer_exp  judge_exp  judge_count  outcome
23108          1      0.0075   0.002712          3.0        0
7691           0      0.0200   0.017627          3.0        0
24664          1      0.0150   0.050847          3.0        0
8845           4      0.0150   0.044068          3.0        0
22645          1      0.0200   0.016271          3.0        0

In [77]:
X=df[['case_type','lawyer_exp','judge_exp','judge_count']]

In [78]:
y=df['outcome']

In [79]:
scaler=StandardScaler()

X=scaler.fit_transform(X)

In [80]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

model=LogisticRegression(max_iter=2000)

model.fit(X_train,y_train)

ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: np.int64(0)

In [81]:
print(y.value_counts())

print(y_train.value_counts())

print(y_test.value_counts())

outcome
0    8094
Name: count, dtype: int64
outcome
0    6475
Name: count, dtype: int64
outcome
0    1619
Name: count, dtype: int64

In [83]:
df['complexity']=( df['judge_count']*2 + np.random.randint(5,20,len(df)) )

df['evidence']=np.random.uniform(0.4,0.9,len(df))

df['win_score']=(
0.30*df['lawyer_exp']+
0.30*df['judge_exp']+
0.20*df['evidence']+
0.20*(1/(df['complexity']/10))
)

In [84]:
df = df.sort_values('win_score')

df['outcome']=0

df.iloc[len(df)//2: , df.columns.get_loc('outcome')] = 1

In [85]:
FEATURES=['case_type','lawyer_exp','judge_exp','judge_count']

X=df[FEATURES]

y=df['outcome']

In [86]:
print(y.value_counts())

outcome
0    4047
1    4047
Name: count, dtype: int64

In [87]:
X_train,X_test,y_train,y_test=train_test_split(
X,y,test_size=0.2,stratify=y)

In [88]:
scaler=StandardScaler()

X_train=scaler.fit_transform(X_train)

X_test=scaler.transform(X_test)

In [89]:
model=LogisticRegression(max_iter=2000)

model.fit(X_train,y_train)

LogisticRegression(max_iter=2000)

In [90]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

pred=model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred))

print(classification_report(y_test,pred))

print(confusion_matrix(y_test,pred))

Accuracy: 0.8597899938233478
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       810
           1       0.91      0.80      0.85       809

    accuracy                           0.86      1619
   macro avg       0.86      0.86      0.86      1619
weighted avg       0.86      0.86      0.86      1619

[[744  66]
 [161 648]]

In [91]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

pred=model.predict(X_test)

print("Accuracy:",accuracy_score(y_test,pred))

print(classification_report(y_test,pred))

print(confusion_matrix(y_test,pred))

Accuracy: 0.8597899938233478
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       810
           1       0.91      0.80      0.85       809

    accuracy                           0.86      1619
   macro avg       0.86      0.86      0.86      1619
weighted avg       0.86      0.86      0.86      1619

[[744  66]
 [161 648]]

In [92]:
prob=model.predict_proba(X_test)

win_prob=prob[:,1]

print(win_prob[:10])

[0.99986955 0.12983499 0.99805477 0.98737865 0.19935462 0.14372597
 0.08267666 0.35217207 0.9999793  0.5247058 ]

In [93]:
import numpy as np

def predict_case(case_type,lawyer_exp,judge_exp,judge_count):

    FEATURES=['case_type','lawyer_exp','judge_exp','judge_count']

    sample=np.array([[case_type,lawyer_exp,judge_exp,judge_count]])

    sample=scaler.transform(sample)

    prob=model.predict_proba(sample)

    win=prob[0][1]*100

    if win>70:
        strength="Strong"

    elif win>50:
        strength="Moderate"

    else:
        strength="Weak"

    return {
        "win_probability":round(win,2),
        "case_strength":strength
    }

In [94]:
predict_case(1,0.3,0.5,3)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

{'win_probability': np.float64(99.8), 'case_strength': 'Strong'}

In [95]:
importance=model.coef_[0]

for i,v in enumerate(importance):
    print(FEATURES[i],":",v)

case_type : -0.004181556184350956
lawyer_exp : 2.095973129012405
judge_exp : 4.277590789773448
judge_count : -0.32579202740419266

In [97]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    random_state=42
)

rf.fit(X_train,y_train)

rf_pred=rf.predict(X_test)

print("RF Accuracy:",accuracy_score(y_test,rf_pred))

RF Accuracy: 0.849289684990735

In [98]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [99]:
from xgboost import XGBClassifier

xgb=XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train,y_train)

xgb_pred=xgb.predict(X_test)

print("XGB Accuracy:",accuracy_score(y_test,xgb_pred))

XGB Accuracy: 0.8560840024706609

In [100]:
prob=xgb.predict_proba(X_test)

print(prob[:5])

[[4.0537119e-04 9.9959463e-01]
 [9.1496539e-01 8.5034616e-02]
 [3.7586689e-04 9.9962413e-01]
 [4.8077106e-04 9.9951923e-01]
 [1.0409379e-01 8.9590621e-01]]

In [102]:
from sklearn.metrics import accuracy_score

# Logistic
log_pred=model.predict(X_test)
accuracy1=accuracy_score(y_test,log_pred)

# Random Forest
rf_pred=rf.predict(X_test)
accuracy2=accuracy_score(y_test,rf_pred)

# XGBoost
xgb_pred=xgb.predict(X_test)
accuracy3=accuracy_score(y_test,xgb_pred)

results={
"Logistic":accuracy1,
"RandomForest":accuracy2,
"XGBoost":accuracy3
}

print(results)

{'Logistic': 0.8597899938233478, 'RandomForest': 0.849289684990735, 'XGBoost': 0.8560840024706609}

In [103]:
for model_name,acc in results.items():
    print(model_name,"Accuracy:",round(acc*100,2),"%")

Logistic Accuracy: 85.98 %
RandomForest Accuracy: 84.93 %
XGBoost Accuracy: 85.61 %

In [104]:
from sklearn.metrics import classification_report

print("Logistic")
print(classification_report(y_test,log_pred))

print("Random Forest")
print(classification_report(y_test,rf_pred))

print("XGBoost")
print(classification_report(y_test,xgb_pred))

Logistic
              precision    recall  f1-score   support

           0       0.82      0.92      0.87       810
           1       0.91      0.80      0.85       809

    accuracy                           0.86      1619
   macro avg       0.86      0.86      0.86      1619
weighted avg       0.86      0.86      0.86      1619

Random Forest
              precision    recall  f1-score   support

           0       0.81      0.91      0.86       810
           1       0.90      0.78      0.84       809

    accuracy                           0.85      1619
   macro avg       0.86      0.85      0.85      1619
weighted avg       0.86      0.85      0.85      1619

XGBoost
              precision    recall  f1-score   support

           0       0.82      0.92      0.86       810
           1       0.91      0.79      0.85       809

    accuracy                           0.86      1619
   macro avg       0.86      0.86      0.86      1619
weighted avg       0.86      0.86      0.86      1619

In [105]:
FEATURES=['case_type','lawyer_exp','judge_exp','judge_count']

importance=model.coef_[0]

for i,v in enumerate(importance):
    print(FEATURES[i],":",round(v,3))

case_type : -0.004
lawyer_exp : 2.096
judge_exp : 4.278
judge_count : -0.326

In [106]:
def predict_case(case_type,lawyer_exp,judge_exp,judge_count):

    sample=np.array([[case_type,lawyer_exp,judge_exp,judge_count]])

    sample=scaler.transform(sample)

    prob=model.predict_proba(sample)

    win=prob[0][1]*100

    if win>70:
        strength="Strong"

    elif win>50:
        strength="Moderate"

    else:
        strength="Weak"

    return {
        "Win probability":round(win,2),
        "Case strength":strength
    }

In [107]:
predict_case(1,0.3,0.5,3)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

{'Win probability': np.float64(99.8), 'Case strength': 'Strong'}

In [108]:
import pickle

pickle.dump(model,open("legal_case_model.pkl","wb"))

pickle.dump(scaler,open("scaler.pkl","wb"))

In [109]:
for i in range(10):

    print(predict_case(
        np.random.randint(0,4),
        np.random.uniform(0,1),
        np.random.uniform(0,1),
        np.random.randint(1,5)
    ))

{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}
{'Win probability': np.float64(99.98), 'Case strength': 'Strong'}
{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}
{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}
{'Win probability': np.float64(99.91), 'Case strength': 'Strong'}
{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}
{'Win probability': np.float64(99.83), 'Case strength': 'Strong'}
{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}
{'Win probability': np.float64(97.94), 'Case strength': 'Strong'}
{'Win probability': np.float64(100.0), 'Case strength': 'Strong'}

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [110]:
pred=model.predict(X_test)

print(np.unique(pred,return_counts=True))

(array([0, 1]), array([905, 714]))

In [113]:
predict_case(0,0.01,0.02,1)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

{'Win probability': np.float64(11.11), 'Case strength': 'Weak'}

In [114]:
predict_case(1,0.02,0.01,1)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

{'Win probability': np.float64(11.03), 'Case strength': 'Weak'}

In [115]:
predict_case(2,0.05,0.03,1)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

{'Win probability': np.float64(18.73), 'Case strength': 'Weak'}

In [116]:
import pandas as pd
import numpy as np

FEATURES=['case_type','lawyer_exp','judge_exp','judge_count']

def predict_case(case_type,lawyer_exp,judge_exp,judge_count):

    sample=pd.DataFrame(
        [[case_type,lawyer_exp,judge_exp,judge_count]],
        columns=FEATURES
    )

    sample=scaler.transform(sample)

    prob=model.predict_proba(sample)

    win=float(prob[0][1]*100)

    if win>70:
        strength="Strong"
    elif win>50:
        strength="Moderate"
    else:
        strength="Weak"

    return {
        "Win probability":round(win,2),
        "Case strength":strength
    }